/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

export const ID_GREEN_BULLET = 'GREEN_BULLET';

export const CanGreenBullet = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('models/green_bullet.glb');

  return (
    <group name={ID_GREEN_BULLET} {...props} dispose={null} ref={ref}>
      <group scale={8}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.CanMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.GREEN_BULLET}
        />
      </group>
    </group>
  );
});

useGLTF.preload('/green_bullet.glb');
