/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

export const ID_HOWLING_WOLF = 'HOWLING_WOLF';

export const CanHowlingWolf = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('models/howling_wolf.glb');

  return (
    <group name={ID_HOWLING_WOLF} {...props} dispose={null} ref={ref}>
      <group scale={8}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.CanMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.HOWLING_WOLF}
        />
      </group>
    </group>
  );
});

useGLTF.preload('/howling_wolf.glb');
